"""add image url to tours

Revision ID: 0be361015d95
Revises: 511ba2a99e57
Create Date: 2026-05-04 23:57:48.320623

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = '0be361015d95'
down_revision: Union[str, None] = '511ba2a99e57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tours', sa.Column('image_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tours', 'image_url')
    # ### end Alembic commands ###